routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', function () {
//    return DB::table('core_users')->get();
// });
Route::get('/login-report',[App\Http\Controllers\ReportHomeController::class, 'login']);
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\ReportHomeController::class, 'index'])->name('home');
    Route::get('/error', function () {
        return view('pages.errors.error');
    })->name('error');
    Route::resource('departments', App\Http\Controllers\DepartmentController::class);
    Route::resource('parties', App\Http\Controllers\PartyController::class);
    Route::get('/reports/loan-request', [App\Http\Controllers\LoanRequestController::class, 'index']);
    Route::get('/reports/loan-created', [App\Http\Controllers\LoanCreatedController::class, 'index']);
    Route::get('/reports/loan-released', [App\Http\Controllers\LoanReleasedController::class, 'index']);
    Route::get('/reports/repaid-amounts', [App\Http\Controllers\RepaidAmountController::class, 'index']);
    Route::get('/reports/interest-accumulated', [App\Http\Controllers\InterestAccumulatedController::class, 'index']);
    Route::get('/reports/saving-account-opened', [App\Http\Controllers\SavingAccountOpenedController::class, 'index']);
    Route::get('/reports/withdrawals', [App\Http\Controllers\WithdrawalController::class, 'index']);
    Route::get('/reports/deposits', [App\Http\Controllers\DepositController::class, 'index']);
    Route::get('/reports/saving-account-closed', [App\Http\Controllers\SavingAccountClosedController::class, 'index']);
    Route::get('/reports/investment-created', [App\Http\Controllers\InvestmentCreatedController::class, 'index']);
    Route::get('/reports/interest-given', [App\Http\Controllers\InterestGivenController::class, 'index']);
    //Route::get('/reports/investment-account-opened', [App\Http\Controllers\InvestmentAccountOpenedController::class, 'index']);
    Route::get('/reports/investment-account-closed', [App\Http\Controllers\InvestmentAccountClosedController::class, 'index']);
    //Route::get('/reports/collection-report', [App\Http\Controllers\CollectionReportController::class, 'collectionReport']);
    Route::get('/reports/collection/officer-wise', [App\Http\Controllers\CollectionReportController::class, 'officerWise']);
    Route::get('/reports/collection/center-wise', [App\Http\Controllers\CollectionReportController::class, 'centerWise']);
    Route::get('/reports/collection/department-wise', [App\Http\Controllers\CollectionReportController::class, 'departmentWise']);

    Route::get('/reports/loans-report', [App\Http\Controllers\LoanReportController::class, 'detailed']);
    Route::get('/reports/loans-combined-summary-report', [App\Http\Controllers\LoanReportController::class, 'combinedSummary']);
    Route::get('/reports/loans-summary-report', [App\Http\Controllers\LoanReportController::class, 'summary']);
    Route::get('/reports/release-report', [App\Http\Controllers\LoanReportController::class, 'release']);
    Route::get('/reports/release-summary', [App\Http\Controllers\LoanReportController::class, 'releaseSummary']);
    Route::get('/reports/collection-report', [App\Http\Controllers\LoanReportController::class, 'collectionDetailed']);
    Route::get('/reports/collection-summary-report', [App\Http\Controllers\LoanReportController::class, 'collectionSummary']);
    Route::get('/reports/debtor-balance-report', [App\Http\Controllers\LoanReportController::class, 'debtorBalance']);
    Route::get('/reports/npl-report', [App\Http\Controllers\LoanReportController::class, 'npl']);
    Route::get('/reports/fees-report', [App\Http\Controllers\LoanReportController::class, 'fees']);
    Route::get('/reports/product-analysis-report', [App\Http\Controllers\LoanReportController::class, 'productAnalysis']);
    Route::get('/reports/csu-analysis-report', [App\Http\Controllers\LoanReportController::class, 'csuAnalysis']);
    Route::get('/reports/branch-analysis-report', [App\Http\Controllers\LoanReportController::class, 'branchAnalysis']);
    

});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Auth;

class Department extends Model
{
    use HasFactory;
    protected $table = 'core_departments';
    protected $keyType = 'string';
    public $incrementing = false;

    protected $fillable = [
            'name',
            'code_name',
            'type',
            'manager_id',
            'supervisor_id',
            'parent_id',
            'logo',
            'created_by',
            'updated_by',
            'deleted_by'
    ];

    public static function boot()
    {
        parent::boot();
        static::creating(function ($department) {
            $department->id = uuid4();
            $department->code_name = 'SE-'.(string)(100001+Department::count());

            if (Auth::check()) {
                $department->created_by = Auth::user()->id;
                $department->updated_by = Auth::user()->id;
            }
        });

        static::updating(function ($department) {
            if (Auth::check()) {
                $department->updated_by = Auth::user()->id;
            }
        });

        static::deleting(function ($department) {
            if (Auth::check()) {
                $department->deleted_by = Auth::user()->id;
                $department->save();
            }
        });
    }

    public function setLogoAttibute($value) {
        if ($value) {
            $imageName = time().'.'.$value->extension();  
            $value->storeAs('logo', $imageName);
            $this->attributes['logo'] = '/logo/'.$imageName;
        }

        $this->attributes['logo'] = null;
    }

    public function parent() {
        return $this->belongsTo(Department::class,'parent_id');
    }

     // this relationship will only return one level of child items
     public function sections(){
         return $this->hasMany(Department::class, 'parent_id');
     }
 
     // This is method where we implement recursive relationship
     public function childSections(){
         return $this->hasMany(Department::class, 'parent_id')->with('sections');
     }
     
     public function childrens(){
        return $this->sections()->with('childrens');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\DepartmentStoreRequest;
use App\Http\Requests\DepartmentUpdateRequest;
use Exception;
use RealRashid\SweetAlert\Facades\Alert;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->is('api*')) {
            $sections = Department::whereNull('parent_id')
            ->with('childrens')
                                ->orderby('name', 'asc')
                                ->get();

            return response()->json([
                "success" => true,
                "message" => "Operation successful.",
                "data" => $sections,
            ],200);
        }

        $sections = Department::whereNull('parent_id')
                                ->with('childSections')
                                ->orderby('name', 'asc')
                                ->get();

        return view('pages.department.index',compact('sections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $current = Department::find($request->pid);
        $root = $this->parentPath($current);
        $users = User::all();
        return view('pages.department.create',compact('root','current','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DepartmentStoreRequest $request)
    {
        DB::beginTransaction();
        try{
            $department = Department::create($request->validated());
            DB::commit();
            toast('Department Created Successfully','success')->timerProgressBar();
            return redirect()->route('departments.index');
        }catch (Exception $th) {
            DB::rollback();
            toast('Oops something went wrong please try again','error')->timerProgressBar();
            return redirect()->route('departments.create');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        $root = $this->parentPath($department->parent);
        $users = User::all();
        return view('pages.department.edit',compact('department','root','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(DepartmentUpdateRequest $request, Department $department)
    {
        try{
            $department->update($request->validated());
            toast('Department Created Successfully','success')->timerProgressBar();
            return redirect()->route('departments.index');
        }catch (Exception $th) {
            toast('Oops something went wrong please try again','error')->timerProgressBar();
            return redirect()->route('departments.edit');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        //
    }

    private function parentPath($currentNode)
    {
        $root = '';
        $patent = $currentNode;
        $roots = [];


        while($patent) {
            $roots[] = $patent->name.' ('.$patent->type.')';
            $patent = $patent->parent;
        }

        foreach (array_reverse($roots) as $key => $value) {
        $root = $root.' / '.$value;
        }
        return $root;
    }
}

resources/views/pages/department/create.blade.php
@extends("layouts.app")

@section('title')
    Create Brand
@endsection

@section('content')
    <h1 class="page-heading rounded d-flex justify-content-between">
        Create Departments
        <span class="text-nowrap bd-highlight fs-6 fw-normal">{{$root}}</span>
    </h1>

    <form novalidate action="{{ route('departments.store') }}" method="POST" enctype='multipart/form-data'>
        @csrf
        <input type="hidden" name="parent_id" value="{{$current ? $current->id : ''}}" />
        <div class="row" id="filter-panel">
            <div class="col-12">
                <div class="my-3 p-3 bg-body rounded shadow-sm">
                    <div class="row">
                        {{-- <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="code_name" class="form-label">Code Name <strong
                                        style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('code_name') is-invalid @enderror"
                                    value="{{ old('code_name') }}" placeholder="Code Name" type="text" name="code_name" />
                                @error('code_name')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div> --}}
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="name" class="form-label">Name <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('name') is-invalid @enderror"
                                    value="{{ old('name') }}" placeholder="Name" type="text" name="name" />
                                @error('name')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="logo" class="form-label">Logo <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('logo') is-invalid @enderror"
                                    value="{{ old('logo') }}" placeholder="Logo" type="file" name="logo" />
                                @error('logo')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="type" class="form-label">Type <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('type') is-invalid @enderror"
                                    value="{{ old('type') }}" placeholder="Type" type="text" name="type" />
                                @error('type')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="manager_id" class="form-label">Manager <strong
                                        style="color:red">*</strong></label>
                                <select class="searchable-select form-control @error('manager_id') is-invalid @enderror"
                                    placeholder="Manager" type="text" name="manager_id" id="manager_id">
                                    <option value="">Any</option>
                                    @foreach ($users as $item)
                                    <option value="{{$item->id}}" {{ old("manager_id") == $item->id ? "selected":"" }}>{{$item->first_name}}</option>
                                    @endforeach
                                </select>
                                @error('manager_id')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="supervisor_id" class="form-label">Supervisor <strong
                                        style="color:red">*</strong></label>
                                <select class="searchable-select form-control @error('supervisor_id') is-invalid @enderror"
                                    placeholder="Supervisor" type="text" name="supervisor_id" id="supervisor_id">
                                    <option value="">Any</option>
                                    @foreach ($users as $item)
                                    <option value="{{$item->id}}">{{$item->first_name}}</option>
                                    @endforeach
                                </select>
                                @error('supervisor_id')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        {{-- <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea class="form-control mx-1" placeholder="Description" type="text"
                                    name="description">{{ old('description') }}</textarea>
                            </div>
                        </div> --}}

                    </div>
                    <div class="row border-top-1 m-0 pt-4 mt-2">
                        <div class="col-12 col-md-3 offset-md-9 d-flex">
                            <button type="button" onclick="window.location.replace(`{{ route('departments.index') }}`)"
                                class="btn btn-primary-inverse w-100 mx-1">BACK</button>
                            <button type="submit" class="btn btn-primary w-100 mx-1">SUBMIT</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
    </script>
@endsection

resources/views/pages/department/edit.blade.php
@extends("layouts.app")

@section('title')
    Create Brand
@endsection

@section('content')
    <h1 class="page-heading rounded d-flex justify-content-between">
        Edit Departments
        <span class="text-nowrap bd-highlight fs-6 fw-normal">{{$root}}</span>
    </h1>

    <form novalidate action="{{ route('departments.update',$department->id) }}" method="POST" enctype='multipart/form-data'>
        @csrf
        @method('put')
        <div class="row" id="filter-panel">
            <div class="col-12">
                <div class="my-3 p-3 bg-body rounded shadow-sm">
                    <div class="row">
                        {{-- <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="code_name" class="form-label">Code Name <strong
                                        style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('code_name') is-invalid @enderror"
                                    value="{{ old('code_name') }}" placeholder="Code Name" type="text" name="code_name" />
                                @error('code_name')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div> --}}
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="name" class="form-label">Name <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('name') is-invalid @enderror"
                                    value="{{ old('name', $department->name) }}" placeholder="Name" type="text" name="name" />
                                @error('name')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="logo" class="form-label">Logo <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('logo') is-invalid @enderror"
                                     placeholder="Logo" type="file" name="logo" />
                                @error('logo')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="type" class="form-label">Type <strong style="color:red">*</strong></label>
                                <input class="form-control mx-1 @error('type') is-invalid @enderror"
                                    value="{{ old('type',$department->type) }}" placeholder="Type" type="text" name="type" />
                                @error('type')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="manager_id" class="form-label">Manager <strong
                                        style="color:red">*</strong></label>
                                <select class="searchable-select form-control @error('manager_id') is-invalid @enderror"
                                    placeholder="Manager" type="text" name="manager_id" id="manager_id">
                                    <option value="">Any</option>
                                    @foreach ($users as $item)
                                    <option value="{{$item->id}}" {{ old("manager_id",$department->manager_id) == $item->id ? "selected":"" }}>{{$item->first_name}}</option>
                                    @endforeach
                                </select>
                                @error('manager_id')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="supervisor_id" class="form-label">Supervisor <strong
                                        style="color:red">*</strong></label>
                                <select class="searchable-select form-control @error('supervisor_id') is-invalid @enderror"
                                    placeholder="Supervisor" type="text" name="supervisor_id" id="supervisor_id">
                                    <option value="">Any</option>
                                    @foreach ($users as $item)
                                    <option value="{{$item->id}}" {{ old("supervisor_id",$department->supervisor_id) == $item->id ? "selected":"" }}>{{$item->first_name}}</option>
                                    @endforeach
                                </select>
                                @error('supervisor_id')
                                    <span class="error invalid-feedback mb-2" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        {{-- <div class="col-12 col-md-4">
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea class="form-control mx-1" placeholder="Description" type="text"
                                    name="description">{{ old('description') }}</textarea>
                            </div>
                        </div> --}}

                    </div>
                    <div class="row border-top-1 m-0 pt-4 mt-2">
                        <div class="col-12 col-md-3 offset-md-9 d-flex">
                            <button type="button" onclick="window.location.replace(`{{ route('departments.index') }}`)"
                                class="btn btn-primary-inverse w-100 mx-1">BACK</button>
                            <button type="submit" class="btn btn-primary w-100 mx-1">SUBMIT</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script>
    </script>
@endsection

resources/views/pages/department/show.blade.php
@extends("layouts.main")

@section('title')
    Brands
@endsection

@section("main-body")

<h1 class="page-heading rounded">Brand - {{$brand->name}}</h1>

<div class="row" id="filter-panel">
    <div class="col-12">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <div class="row">
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <p for="name" class="form-label"><b>Name :</b> {{ $brand->name }}</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <p for="description" class="form-label"><b>Description :</b> {{ $brand->description }}</p>
                    </div>
                </div>
                <div class="row border-top-1 m-0 pt-4 mt-2">
                    <div class="col-12 col-md-3 offset-md-9 d-flex">
                        <a href="{{ route('brands.index') }}" class="btn btn-primary-inverse w-100 mx-1">BACK</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/department/sub_sections.blade.php
<li id="{{$sub_sections->name}}">
  <span class="d-flex align-items-center justify-content-between">
    <div id={{$sub_sections->name}} class="d-flex">
      <div ><i class="fas fa-circle" style="color:black"></i></div>
      <div class="ps-2">{{ $sub_sections->name }}</div>
      <div style="color:gray;padding-left:1px">{{ ' | ' . $sub_sections->type }}</div>
  </div>
    <div>
      <a href="{{route('departments.create',['pid' =>$sub_sections->id])}}"class="btn btn-primary btn-sm"><i class="fas fa-plus"></i></a>
      <a  href="{{route('departments.edit',['department' =>$sub_sections->id, 'type' =>'sub'])}}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
      <a href="{{route('departments.show',$sub_sections->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
      <button myid='{{$sub_sections->id}}' onclick="archiveFunction('{{$sub_sections->type.'-'.$sub_sections->name}}','{{$sub_sections->id}}')" style="margin-right: 5px" href="" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
      <a hidden id="{{$sub_sections->id}}" href="" class="btn btn-primary btn-sm"><i class="fas fa-trash-alt"></i></a>
    </div> 
  </span>
    @if ($sub_sections->sections)
      <ul>
        @if(count($sub_sections->sections) > 0)
            @foreach ($sub_sections->sections as $subSections)
                @include('pages.department.sub_sections', ['sub_sections' => $subSections])
            @endforeach
        @endif
      </ul>
    @endif
</li>

<script>

</script>