routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', function () {
//    return DB::table('core_users')->get();
// });
Route::get('/login-report',[App\Http\Controllers\ReportHomeController::class, 'login']);
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [App\Http\Controllers\ReportHomeController::class, 'index'])->name('home');
    Route::get('/error', function () {
        return view('pages.errors.error');
    })->name('error');
    Route::resource('departments', App\Http\Controllers\DepartmentController::class);
    Route::resource('parties', App\Http\Controllers\PartyController::class);
    Route::get('/reports/loan-request', [App\Http\Controllers\LoanRequestController::class, 'index']);
    Route::get('/reports/loan-created', [App\Http\Controllers\LoanCreatedController::class, 'index']);
    Route::get('/reports/loan-released', [App\Http\Controllers\LoanReleasedController::class, 'index']);
    Route::get('/reports/repaid-amounts', [App\Http\Controllers\RepaidAmountController::class, 'index']);
    Route::get('/reports/interest-accumulated', [App\Http\Controllers\InterestAccumulatedController::class, 'index']);
    Route::get('/reports/saving-account-opened', [App\Http\Controllers\SavingAccountOpenedController::class, 'index']);
    Route::get('/reports/withdrawals', [App\Http\Controllers\WithdrawalController::class, 'index']);
    Route::get('/reports/deposits', [App\Http\Controllers\DepositController::class, 'index']);
    Route::get('/reports/saving-account-closed', [App\Http\Controllers\SavingAccountClosedController::class, 'index']);
    Route::get('/reports/investment-created', [App\Http\Controllers\InvestmentCreatedController::class, 'index']);
    Route::get('/reports/interest-given', [App\Http\Controllers\InterestGivenController::class, 'index']);
    //Route::get('/reports/investment-account-opened', [App\Http\Controllers\InvestmentAccountOpenedController::class, 'index']);
    Route::get('/reports/investment-account-closed', [App\Http\Controllers\InvestmentAccountClosedController::class, 'index']);
    //Route::get('/reports/collection-report', [App\Http\Controllers\CollectionReportController::class, 'collectionReport']);
    Route::get('/reports/collection/officer-wise', [App\Http\Controllers\CollectionReportController::class, 'officerWise']);
    Route::get('/reports/collection/center-wise', [App\Http\Controllers\CollectionReportController::class, 'centerWise']);
    Route::get('/reports/collection/department-wise', [App\Http\Controllers\CollectionReportController::class, 'departmentWise']);

    Route::get('/reports/loans-report', [App\Http\Controllers\LoanReportController::class, 'detailed']);
    Route::get('/reports/loans-combined-summary-report', [App\Http\Controllers\LoanReportController::class, 'combinedSummary']);
    Route::get('/reports/loans-summary-report', [App\Http\Controllers\LoanReportController::class, 'summary']);
    Route::get('/reports/release-report', [App\Http\Controllers\LoanReportController::class, 'release']);
    Route::get('/reports/release-summary', [App\Http\Controllers\LoanReportController::class, 'releaseSummary']);
    Route::get('/reports/collection-report', [App\Http\Controllers\LoanReportController::class, 'collectionDetailed']);
    Route::get('/reports/collection-summary-report', [App\Http\Controllers\LoanReportController::class, 'collectionSummary']);
    Route::get('/reports/debtor-balance-report', [App\Http\Controllers\LoanReportController::class, 'debtorBalance']);
    Route::get('/reports/npl-report', [App\Http\Controllers\LoanReportController::class, 'npl']);
    Route::get('/reports/fees-report', [App\Http\Controllers\LoanReportController::class, 'fees']);
    Route::get('/reports/product-analysis-report', [App\Http\Controllers\LoanReportController::class, 'productAnalysis']);
    Route::get('/reports/csu-analysis-report', [App\Http\Controllers\LoanReportController::class, 'csuAnalysis']);
    Route::get('/reports/branch-analysis-report', [App\Http\Controllers\LoanReportController::class, 'branchAnalysis']);
    

});

app/Models/Party.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Model;
use Auth;
use App\Permissions\HasPermissionsTrait;

class Party extends Authenticatable
{
    use HasApiTokens,HasPermissionsTrait, HasFactory, Notifiable;
    protected $table = 'core_parties';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = ['user_id','type'];

    
    protected $keyType = 'string';
    public $incrementing = false;

    public static function boot()
    {
        parent::boot();
        static::creating(function($user)
        {
            $user->id = uuid4();

            if(Auth::check()){
                $user->created_by = Auth::user()->id;
                $user->updated_by = Auth::user()->id;
            }
        });

        static::updating(function($user)
        {
            if(Auth::check()){
                $user->updated_by = Auth::user()->id;
            }
        });

        static::deleting(function($user)
        {
            if(Auth::check()){
                $user->deleted_by = Auth::user()->id;
            }
        });
    }

 
}

app/Http/Controllers/PartyController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Party;
use App\Models\Address;
use App\Http\Controllers\Controller;
use App\Http\Requests\PartyStoreRequest;
use App\Models\Department;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;

class PartyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->is('api*')) {

            
            //$user = $request->is('api*') ? Auth::guard('api')->user() : Auth::user();
            $search = $request->search;
            $sortBy = $request->sortBy ? $request->sortBy : 'core_users.created_at';
            $sortDirection = $request->sortDirection ? $request->sortDirection : 'asc';
            $pagePer = $request->pagePer ? $request->pagePer  :Config::get('constant.pagination');
            $parties = Party::select('core_users.id','core_users.title','core_users.first_name','core_users.last_name','core_users.contact_primary','core_users.email','core_users.status',
                            'core_parties.type','core_users.id')               
                            ->leftjoin('core_users','core_parties.user_id','=','core_users.id')
                            ->where('core_users.first_name' ,'LIKE' ,"%$search%")
                            ->orWhere('core_users.last_name' ,'LIKE' ,"%$search%")
                            ->orWhere('core_users.contact_primary' ,'LIKE' ,"%$search%")
                            ->orWhere('core_users.identifier_value' ,'LIKE' ,"%$search%")
                            ->orWhere('core_users.email' ,'LIKE' ,"%$search%")
                            ->orderBy($sortBy,$sortDirection)
                            ->paginate($pagePer);
            
                return response()->json([
                    "success" => true,
                    "message" => "Operation successful.",
                    "data" => $parties,
              ],200);
        }

        $search = $request->search;
        $sortBy = $request->sortBy ? $request->sortBy : 'core_users.created_at';
        $sortDirection = $request->sortDirection ? $request->sortDirection : 'asc';
        $pagePer = $request->pagePer ? $request->pagePer  :Config::get('constant.pagination');
        $parties = Party::select('core_users.id','core_users.title','core_users.first_name','core_users.last_name','core_users.contact_primary','core_users.email','core_users.status',
                        'core_parties.type','core_users.id')               
                        ->leftjoin('core_users','core_parties.user_id','=','core_users.id')
                        ->where('core_users.department_id','=',Auth::user()->department_id)
                        ->where('core_users.first_name' ,'LIKE' ,"%$search%")
                        ->orWhere('core_users.last_name' ,'LIKE' ,"%$search%")
                        ->orWhere('core_users.contact_primary' ,'LIKE' ,"%$search%")
                        ->orWhere('core_users.identifier_value' ,'LIKE' ,"%$search%")
                        ->orWhere('core_users.email' ,'LIKE' ,"%$search%")
                        ->orderBy($sortBy,$sortDirection)
                        ->paginate($pagePer);
        $departments = Department::whereNull('parent_id')->get();


        return view('pages.party.index',compact('parties','search','sortBy','sortDirection','pagePer','departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.party.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PartyStoreRequest $request)
    {
        try{
            $user = User::create($request->validated());
            
            $address=new Address();
            $address->city=$request->city;
            $address->province=$request->province;
            $address->district=$request->district;
            $address->gsdivision=$request->gsdivision;
            $address->residential_address=$request->residential_address;
            $address->official_address=$request->official_address;
            $address->user_id=$user->id;
            $address->save();
            
            $party = new Party();
            $party->user_id = $user->id;   
            $party->type = $request->type;   
            $party->save();

            if ($request->is('api*')) {
                return response()->json([
                    "success" => true,
                    "message" => "Operation successful.",
                    "data" => $user,
                ],200);
            }

            return redirect()->route('parties.index');
        }catch (\Exception $th) {
            dd($th->getMessage());
            return redirect()->route('parties.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        if ($request->is('api*')) {
            
            $user = User::find($id);
            $address = Address::where('core_addresses.user_id','=',$user->id)->first();
            $party = Party::where('core_parties.user_id','=',$user->id)->first();
            
            $responseData = compact('user','address','party');

            return response()->json([
                "success" => true,
                "message" => "Operation successful.",
                "data" => $responseData,
            ],200);
        }
        $user = User::find($id);
        $address = Address::where('core_addresses.user_id','=',$user->id)->first();
        $party = Party::where('core_parties.user_id','=',$user->id)->first();
        return view('pages.party.show',compact('user','address','party'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $address = Address::where('core_addresses.user_id','=',$user->id)->first();
        $party = Party::where('core_parties.user_id','=',$user->id)->first();
        return view('pages.party.edit',compact('user','address','party'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(PartyStoreRequest $request, $id)
    {
            try {

                if ($request->is('api*')) {

                    $user = User::find($id);
                    $user->title=$request->title;
                    $user->identifier_value=$request->identifier_value;
                    $user->first_name=$request->first_name;
                    $user->last_name=$request->last_name;
                    $user->middle_name=$request->middle_name;
                    $user->dob=$request->dob;
                    $user->dp=$request->dp;
                    $user->gender=$request->gender;
                    $user->maritial_status=$request->maritial_status;
                    $user->nationality=$request->nationality;
                    $user->contact_primary=$request->contact_primary;
                    $user->email=$request->email;
                    $user->save();
                    
                    $address = Address::where('core_addresses.user_id','=',$user->id)->first();
                    $address->city=$request->city;
                    $address->province=$request->province;
                    $address->district=$request->district;
                    $address->gsdivision=$request->gsdivision;
                    $address->residential_address=$request->residential_address;
                    $address->official_address=$request->official_address;
                    $address->user_id=$user->id;
                    $address->save();

                    $party = Party::where('core_parties.user_id','=',$user->id)->first();
                    $party->user_id = $user->id;   
                    $party->type = $request->type;   
                    $party->save();
                
                    
                    return response()->json([
                        "success" => true,
                        "message" => "Operation successful.",
                        "data" => $user,
                    ],200);
                }
                
                $user = User::find($id);
                $user->title=$request->title;
                $user->identifier_value=$request->identifier_value;
                $user->first_name=$request->first_name;
                $user->last_name=$request->last_name;
                $user->middle_name=$request->middle_name;
                $user->dob=$request->dob;
                $user->dp=$request->dp;
                $user->gender=$request->gender;
                $user->maritial_status=$request->maritial_status;
                $user->nationality=$request->nationality;
                $user->contact_primary=$request->contact_primary;
                $user->email=$request->email;
                $user->save();
                
                $address = Address::where('core_addresses.user_id','=',$user->id)->first();
                $address->city=$request->city;
                $address->province=$request->province;
                $address->district=$request->district;
                $address->gsdivision=$request->gsdivision;
                $address->residential_address=$request->residential_address;
                $address->official_address=$request->official_address;

resources/views/pages/party/index.blade.php
@extends("layouts.app")

@section('title')
    Parties
@endsection

@section("content")

<form novalidate action="{{ route('parties.index') }}" method="GET" onsubmit="$('.page-loader').show()">
    <div class="row">
        <div class="col-md-4">
            <h1 class="page-heading rounded">Parties <span class="badge rounded-pill bg-warning text-white ms-3">{{$parties->total()}}</span></h1>
        </div>
        <div class="col-md-8">
            <div class="filter-cont">
                <div class="row">
                    <div class="col-md-6 col-6 d-flex search-box">
                        <input type="text"  class="form-control" name="search" value="{{$search}}" placeholder="Search"/>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                    <div class="col-md-2 col-4">
                        <button type="button" class="btn btn-primary btn-primary-inverse mt-2 mt-md-0" id="btn-filter">
                            <i class="fas fa-filter"></i> FILTER
                        </button>
                    </div>
                    <div class="col-md-3 col-3">
                        <a href="{{route('parties.create')}}" class="btn btn-primary btn-primary-inverse float-end">
                            <i class="fas fa-plus mx-1"></i> <span class="">ADD NEW</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="display:none" id="filter-panel">
        <div class="col-12">
            <div class="my-3 p-3 bg-body rounded shadow-sm">
                @include('include.filter',['sortBy' => $sortBy,'sortDirection' => $sortDirection,'pagePer' => $pagePer,
                    'sortByArray' => ['name' => "Name" , 'description' => "Description"]])
                <div class="row border-top-1 pt-4 mt-2">
                    <div class="col-12 col-md-3 offset-md-9 d-flex">
                        <button type="reset" class="btn btn-primary-inverse w-100 mx-1">RESET</button>
                        <button type="submit" class="btn btn-primary w-100 mx-1">SUBMIT</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="row mt-1">
    <div class="col-12">
        <div class="my-3 p-1 px-3 bg-white rounded shadow-md ">
            <table class="table table-mobile card-row data-table" id="data-table">
                <thead>
                    <tr id="thead-data">
                        <th class="col-xs">Name</th>
                        <th class="col-xs">Contact No</th>
                        <th class="col-xs">Email</th>
                        <th class="col-xs">Type</th>
                        <th class="col-xs no-sort">Actions</th>
                    </tr>
                </thead>
                <tbody id="tbody-data">
                    @foreach ($parties as $obj)
                        <tr>
                            <td>{{$obj->title}} {{'.'}} {{$obj->first_name}}</td>
                            <td>{{ $obj->contact_primary ?? "-" }}</td>
                            <td>{{ $obj->email ?? "-" }}</td>
                            <td>{{ $obj->type ?? "-" }}</td>
                            <td>
                                <div class="d-flex">
                                    <a href="{{ route('parties.show',[$obj->id]) }}"  title="View" class="btn btn-sm btn-info text-white btn-action"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('parties.edit', $obj->id) }}" title="Edit" class="btn mx-1 btn-sm btn-primary btn-action"><i class="fas fa-edit"></i></a>
                                   <form novalidate action="{{ route('parties.destroy',$obj->id) }}" class="confirm-action" title="Delete" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger  mx-1 btn-action"><i class="fas fa-trash"></i></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="d-flex justify-content-center pagintation-cont">
                {!! $parties->appends($_GET)->links("others.pagination-tiles") !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section("scripts")
<script>
</script>
@endsection

resources/views/pages/party/show.blade.php
@extends("layouts.app")

@section("title")
    <title>View Party</title>
@endsection

@section('content')
<h1 class="page-heading rounded">View Party</h1>

<div class="row" id="filter-panel">
    <div class="col-12">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <div class="row">
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="type" class="form-label">Type</label>
                        <p>{{$party->type }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="identifier_value" class="form-label">Nic Number</label>
                        <p>{{$user->identifier_value}}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="identifier_value" class="form-label">Nic Number</label>
                        <p>{{$user->identifier_value}}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="title" class="form-label">Title</label>
                        <p>{{$user->title }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="first_name" class="form-label">First Name</label>
                        <p>{{$user->first_name }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="middle_name" class="form-label">Middle Name</label>
                        <p>{{$user->middle_name}}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="last_name" class="form-label">Last Name</label>
                        <p>{{$user->last_name}}</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="dob" class="form-label">DOB</label>
                        <p>{{$user->dob}}</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="gender" class="form-label">Gender</label>
                        <p>{{$user->gender}}</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="maritial_status" class="form-label">Martial Status</label>
                        <p>{{ $user->maritial_status }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="nationality" class="form-label">Nationality</label>
                        <p>{{ $user->nationality }}</p>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="contact_primary" class="form-label">Phone Number</label>
                        <p>{{ $user->contact_primary }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="email" class="form-label">Email Address</label>
                        <p>{{ $user->email }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="email" class="form-label">Province</label>
                        <p>{{ $address->province }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="district" class="form-label">District</label>
                        <p>{{ $address->district }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="city" class="form-label">City</label>
                        <p>{{ $address->city }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="gsdivision" class="form-label">GS Division</label>
                        <p>{{ $address->gsdivision }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="residential_address" class="form-label">Residential Address</label>
                        <p>{{ $address->residential_address }}</p>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="mb-3">
                        <label for="official_address" class="form-label">Official Address</label>
                        <p>{{ $address->official_address }}</p>
                    </div>
                </div>

            </div>
            <div class="col-md-4 offset-md-8 col-12 mt-4">
                <button type="button" onclick="window.location.replace(`{{ route('parties.index') }}`)" class="btn btn-primary-inverse w-100 mx-1">BACK</button>
            </div>
        </div>
    </div>
</div>                    
@endsection